language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
env:
  global:
    - CONDA_DEPS="pip flake8 pytest numpy scipy"
    - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
    - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
    - EXTRA_PIP_FLAGS="--find-links=$EXTRA_WHEELS"
    - PRE_PIP_FLAGS="--pre $EXTRA_PIP_FLAGS --find-links $PRE_WHEELS"

matrix:
  include:
    - os: osx
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh"
    - os: osx
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - os: linux
      env:
         - PYTHON_VERSION=2.7
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh"
         - EXTRA_PIP_FLAGS="$PRE_PIP_FLAGS"
    - os: linux
      env:
         - PYTHON_VERSION=3.5
         - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
         - EXTRA_PIP_FLAGS="$PRE_PIP_FLAGS"

before_install:
# https://github.com/travis-ci/travis-ci/issues/6522
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then rvm get head || true; fi
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- echo $MINICONDA_URL
- wget $MINICONDA_URL -O miniconda.sh;
- bash miniconda.sh -b -s -f -p $MINICONDA;
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda config --add channels conda-forge
- conda install --quiet python=$PYTHON_VERSION $CONDA_DEPS

install:
- pip install $EXTRA_PIP_FLAGS ".[analysis]"

script:
- py.test

after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)

cache: false

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
    condition: $PYTHON_VERSION = "3.5"
