language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
env:
  global:
    - CONDA_DEPS="pip flake8 pytest numpy scipy"
    - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
    - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
    - EXTRA_PIP_FLAGS="--find-links=$EXTRA_WHEELS"
    - PRE_PIP_FLAGS="--pre $EXTRA_PIP_FLAGS --find-links $PRE_WHEELS"

matrix:
  include:
    - os: osx
      python: 2.7
    - os: osx
      python: 3.5
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 2.7
      env:
         - EXTRA_PIP_FLAGS="$PRE_PIP_FLAGS"
    - os: linux
      python: 3.5
      env:
         - EXTRA_PIP_FLAGS="$PRE_PIP_FLAGS"

before_install:
    - travis_retry pip install --upgrade pip
    - travis_retry pip install --upgrade virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - travis_retry pip install -U pip wheel  # needed at one point
    - travis_retry pip install pytest pytest-xdist coveralls codecov

install:
- pip install $EXTRA_PIP_FLAGS ".[analysis]"

script:
- py.test -n auto

after_success:
- coveralls
- bash <(curl -s https://codecov.io/bash)

cache: false

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
    condition: $PYTHON_VERSION = "3.5"
