version: 2
jobs:
  build_docs:
    docker:
      - image: python:3.7.4
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python -m venv /tmp/venv
            source /tmp/venv/bin/activate
      - run:
          name: Check Python version and upgrade pip
          command: |
            which python
            python --version
            python -m pip install --upgrade pip setuptools
      - run:
          name: Install PyBIDS
          command: python -m pip install -e ".[doc]"
      - run:
          name: Build documentation
          command: make -C doc html
      - store_artifacts:
          path: /home/circleci/pybids/docs/_build/html

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
